-- =====================================================
-- Sample Oracle DDL Script
-- =====================================================

CREATE TABLE ODS.CUSTOMERS (
    CUSTOMER_ID      NUMBER(10)       NOT NULL,
    CUSTOMER_NAME    VARCHAR2(100),
    EMAIL_ID         VARCHAR2(150),
    PHONE_NUMBER     VARCHAR2(20),
    CREATED_DATE     DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE STG.ORDERS (
    ORDER_ID         NUMBER(10)       NOT NULL,
    CUSTOMER_ID      NUMBER(10),
    ORDER_DATE       DATE,
    ORDER_AMOUNT     NUMBER(12,2),
    CREATED_DATE     DATE DEFAULT SYSDATE,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID)
);

CREATE TABLE EDW.PRODUCTS (
    PRODUCT_ID       NUMBER(10)       NOT NULL,
    PRODUCT_NAME     VARCHAR2(100),
    PRODUCT_CATEGORY VARCHAR2(50),
    PRICE            NUMBER(10,2),
    CREATED_DATE     DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);